on:
    push:
        branches:
            - main
    
    pull_request:
        branches:
            - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    docker:
        runs-on: self-hosted

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4
            
            - 
                name: Log in to the Container registry
                uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -
                name: Build and push development image
                id: build-and-push-dev
                run: |
                    docker build -t $(echo ${{ env.REGISTRY }} | tr '[:upper:]' '[:lower:]')/$(echo ${{ env.IMAGE_NAME }} | tr '[:upper:]' '[:lower:]'):dev --target development .
                    docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
            
            - 
                id: build-and-push
                name: Build and push
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

            -
                name: Generate artifact attestation
                uses: actions/attest-build-provenance@v1
                with:
                    subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
                    subject-digest: ${{ steps.build-and-push.outputs.digest }}
                    push-to-registry: true
