on:
    push:
        branches:
            - main
        tags:
            - 'v*'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    docker:
        runs-on: self-hosted

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4
            
            - 
                name: Log in to the Container registry
                uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            - 
                name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                    tags: |
                        type=match,pattern=v(.*)|latest
                        type=raw,value=latest,enable={{is_default_branch}}
        
            - 
                name: Build
                uses: docker/build-push-action@v2
                with:
                    context: .
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}