on:
    push:
        branches:
            - main
    
    pull_request:
        branches:
            - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: $(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

jobs:
    docker:
        runs-on: self-hosted

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4
            
            - 
                name: Log in to the Container registry
                uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -
                name: Build and push development image
                id: build-and-push-dev
                run: |
                    docker build -t ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:dev --target development .
                    docker push ${{ env.REGISTRY}}/${{ env.IMAGE_NAME }}:dev
            
            - 
                id: build-and-push-prod
                name: Build and push production image
                uses: docker/build-push-action@v6
                with:
                    context: .
                    push: true
                    tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:prod
