on:
    push:
        branches:
            - main
    
    pull_request:
        branches:
            - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
    docker:
        runs-on: self-hosted

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            - 
                name: Checkout
                uses: actions/checkout@v4
            
            - 
                name: Log in to the Container registry
                uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -
                name: Build and push development image
                id: build-and-push-dev
                run: |
                    IMAGE_NAME=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
                    docker build -t ${{ env.REGISTRY}}/${IMAGE_NAME}:dev --target development .
                    docker push ${{ env.REGISTRY}}/${IMAGE_NAME}:dev
            
            - 
                id: build-and-push-prod
                name: Build and push production image
                run: |
                    IMAGE_NAME=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
                    docker build -t ${{ env.REGISTRY}}/${IMAGE_NAME}:prod --target production .
                    docker push ${{ env.REGISTRY}}/${IMAGE_NAME}:prod